# Generated by Django 4.1.3 on 2022-11-27 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_photo_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuseumPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('painter', models.CharField(max_length=100)),
                ('img_path', models.ImageField(blank=True, null=True, upload_to='museum_images/')),
                ('tags', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='museumphoto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.museumphoto'),
        ),
    ]
