# Generated by Django 4.1.3 on 2022-11-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_photo_dalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='prompt',
            field=models.TextField(default=None, null=True),
        ),
    ]
